apiVersion: apps/v1
kind: Deployment
metadata:
  name: barramento-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barramento-de-eventos
  template:
    metadata:
      labels:
        app: barramento-de-eventos
    spec:
      containers:
        - name: barramento-de-eventos
          image: rodbossini/ecm516-20242-barramento
---
apiVersion: v1
kind: Service
metadata:
  name: barramento-service
spec:
  selector:
    app: barramento-de-eventos
  type: ClusterIP
  ports:
    - name: barramento-de-eventos
      protocol: TCP
      port: 10000
      targetPort: 10000
