apiVersion: v1
kind: Pod
metadata:
  name: lembretes
spec:
  containers:
    - name: lembretes
      image:  rodbossini/ecm516-20242-lembretes:0.0.1
      resources:
        limits:
          memory: 256Mi
          cpu: 1 